# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-14 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200413_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='category',
            name='email',
        ),
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
    ]
